import { Html, Head, Main, NextScript } from "next/document";

export default function Document() {
  return (
    <Html lang="en">
      <Head>
        <meta name="GoGas" content="GoGas Web App" />
        <meta name="description" content="Generated by create next app" />
        <meta name="theme-color" content="#ffffff" />
        <meta name="gogas" content="nextjs, next15, pwa, next-pwa" />

        {/* PWA Manifest */}
        <link rel="manifest" href="/manifest.json" />

        {/* Icons */}
        <link rel="apple-touch-icon" href="/icons/logo-gagas-512.png" />
        <link
          rel="icon"
          type="image/png"
          sizes="512x512"
          href="/icons/logo-gagas-512.png"
        />

        {/* Authors */}
        <meta name="author" content="Shaikh Akbar" />
        <link
          rel="author"
          href="https://www.linkedin.com/in/shaikh-akbar-ahmed-1934901ab/"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
        />
      </Head>
      <body className="antialiased">
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}
